# Generated by Django 3.2.12 on 2022-07-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReviewVoting',
            new_name='ProjectReviewVoting',
        ),
    ]
